defmodule Atlas.Lexicon do
  @moduledoc """
  Context module for the brain's own lexicon facts.

  This is the durable store. `Brain.Lexicon.UserDefined` loads it into ETS at
  boot and writes through it, so reads never touch the database.

  Writes are upserts keyed on `Atlas.Schemas.LexiconFact.identity_fields/0`,
  which makes seeding idempotent: running a seeder twice leaves one row per
  fact, with the latest value.
  """

  import Ecto.Query

  alias Atlas.Repo
  alias Atlas.Schemas.LexiconFact

  # Stay well under Postgres' 65,535 bind-parameter limit. A fact row has
  # fourteen columns, so a chunk of 1,000 binds 14,000 parameters.
  @chunk_size 1_000

  # Replaced when a fact that already exists is written again. `frequency` is
  # deliberately absent: re-running a seeder must not reset how often a fact
  # has been observed.
  @replace_on_conflict [:value, :confidence, :archived, :last_observed_at, :updated_at]

  @doc "Inserts a fact, or updates the existing fact with the same identity."
  @spec upsert_fact(map()) :: {:ok, LexiconFact.t()} | {:error, Ecto.Changeset.t()}
  def upsert_fact(attrs) when is_map(attrs) do
    %LexiconFact{}
    |> LexiconFact.changeset(attrs)
    |> Repo.insert(
      on_conflict: {:replace, @replace_on_conflict},
      conflict_target: LexiconFact.identity_fields(),
      returning: true
    )
  end

  @doc """
  Upserts many facts at once.

  Every entry is validated before anything is written. If any entry is
  invalid, nothing is written and `{:error, {index, changeset}}` names the
  first bad entry — a partial seed is never left behind.

  Returns `{:ok, count}`, where `count` includes rows that were updated.
  """
  @spec upsert_facts([map()]) ::
          {:ok, non_neg_integer()} | {:error, {non_neg_integer(), Ecto.Changeset.t()}}
  def upsert_facts(attrs_list) when is_list(attrs_list) do
    validated =
      attrs_list
      |> Enum.with_index()
      |> Enum.reduce_while({:ok, []}, fn {attrs, index}, {:ok, acc} ->
        changeset = LexiconFact.changeset(%LexiconFact{}, attrs)

        if changeset.valid? do
          {:cont, {:ok, [Ecto.Changeset.apply_changes(changeset) | acc]}}
        else
          {:halt, {:error, {index, changeset}}}
        end
      end)

    case validated do
      {:ok, facts} -> {:ok, insert_all(Enum.reverse(facts))}
      {:error, _} = error -> error
    end
  end

  @doc "Returns every fact, archived ones included, so decay state survives a restart."
  @spec list_facts() :: [LexiconFact.t()]
  def list_facts do
    LexiconFact
    |> order_by([f], asc: f.word, asc: f.kind, asc: f.key, asc: f.ref, asc: f.source)
    |> Repo.all()
  end

  @doc "Returns every fact about one word."
  @spec list_facts_for_word(String.t()) :: [LexiconFact.t()]
  def list_facts_for_word(word) when is_binary(word) do
    LexiconFact
    |> where([f], f.word == ^word)
    |> order_by([f], asc: f.kind, asc: f.key, asc: f.ref, asc: f.source)
    |> Repo.all()
  end

  @doc """
  Returns every fact about any of the given words.

  Used after a bulk write to refresh only the words that changed, instead of
  reloading the whole lexicon.
  """
  @spec list_facts_for_words([String.t()]) :: [LexiconFact.t()]
  def list_facts_for_words([]), do: []

  def list_facts_for_words(words) when is_list(words) do
    LexiconFact
    |> where([f], f.word in ^words)
    |> order_by([f], asc: f.word, asc: f.kind, asc: f.key, asc: f.ref, asc: f.source)
    |> Repo.all()
  end

  @doc "Updates an existing fact."
  @spec update_fact(LexiconFact.t(), map()) ::
          {:ok, LexiconFact.t()} | {:error, Ecto.Changeset.t()}
  def update_fact(%LexiconFact{} = fact, attrs) when is_map(attrs) do
    fact
    |> LexiconFact.changeset(attrs)
    |> Repo.update()
  end

  @doc "Counts facts, optionally restricted to one source."
  @spec count_facts(String.t() | nil) :: non_neg_integer()
  def count_facts(source \\ nil)

  def count_facts(nil), do: Repo.aggregate(LexiconFact, :count)

  def count_facts(source) when is_binary(source) do
    LexiconFact
    |> where([f], f.source == ^source)
    |> Repo.aggregate(:count)
  end

  # insert_all bypasses autogenerated ids and timestamps, so both are set here.
  defp insert_all(facts) do
    now = DateTime.utc_now()

    facts
    |> Enum.map(fn fact ->
      fact
      |> Map.from_struct()
      |> Map.drop([:__meta__])
      |> Map.merge(%{id: Ecto.UUID.generate(), inserted_at: now, updated_at: now})
    end)
    |> Enum.chunk_every(@chunk_size)
    |> Enum.reduce(0, fn chunk, total ->
      {count, _} =
        Repo.insert_all(LexiconFact, chunk,
          on_conflict: {:replace, @replace_on_conflict},
          conflict_target: LexiconFact.identity_fields()
        )

      total + count
    end)
  end
end
