defmodule Brain.Analysis.HeuristicStore do
  @moduledoc """
  Stores and matches heuristics with namespaced scopes.

  Heuristics are shortcuts that allow fast-path responses without
  full analysis. They are organized by scope:

  - :global - Apply to all users across all worlds (seeded bootstrap data, max boost: 0.40)
  - :world - Apply to all users within a specific training world (max boost: 0.35)
  - :cohort - Apply to a user group within a world (max boost: 0.25)
  - :user - Apply to a single user (max boost: 0.15)

  This prevents learned heuristics from one world contaminating another,
  and ensures user-specific heuristics don't leak to other users.

  ## World Scoping

  Learned heuristics are stored per-world in training world folders:
  - `priv/training_worlds/<world_id>/heuristics.json`

  Seeded heuristics (global scope) are loaded from:
  - `data/heuristics/seeded_heuristics.json` (generated by scripts/generate_heuristics.py)
  """

  use GenServer
  require Logger

  alias Brain.ML.Tokenizer

  # ETS tables for fast lookups
  @global_table :heuristics_global
  @world_table :heuristics_world
  @cohort_table :heuristics_cohort
  @user_table :heuristics_user
  @stats_table :heuristics_stats

  # Scope configurations
  @scope_config %{
    global: %{max_boost: 0.40, min_successes: 3, table: @global_table},
    world: %{max_boost: 0.35, min_successes: 3, table: @world_table},
    cohort: %{max_boost: 0.25, min_successes: 4, table: @cohort_table},
    user: %{max_boost: 0.15, min_successes: 5, table: @user_table}
  }

  @max_failure_rate 0.20
  @deprecation_days 30

  # Heuristic struct
  defmodule Heuristic do
    @moduledoc "Represents a single heuristic pattern."

    defstruct [
      :id,
      :scope,
      :scope_id,
      :world_id,
      :pattern,
      :conclusion,
      :source,
      :max_activation_boost,
      success_count: 0,
      failure_count: 0,
      last_used: nil,
      last_updated: nil,
      created_at: nil,
      deprecated: false
    ]

    @type t :: %__MODULE__{
            id: String.t(),
            scope: :global | :world | :cohort | :user,
            scope_id: String.t() | nil,
            world_id: String.t() | nil,
            pattern: map(),
            conclusion: map(),
            source: :seeded | :learned,
            max_activation_boost: float(),
            success_count: non_neg_integer(),
            failure_count: non_neg_integer(),
            last_used: integer() | nil,
            last_updated: integer() | nil,
            created_at: integer() | nil,
            deprecated: boolean()
          }
  end

  # Client API

  def start_link(opts \\ []) do
    GenServer.start_link(__MODULE__, opts, name: __MODULE__)
  end

  @doc """
  Matches input against heuristics and returns the best match.

  Requires world_id to ensure world isolation of learned heuristics.
  Returns {:ok, heuristic, confidence} or {:error, :no_match}
  """
  def match_best(text, world_id, user_id \\ nil, cohort_id \\ nil)

  def match_best(_text, nil, _user_id, _cohort_id) do
    Logger.warning("HeuristicStore.match_best called without world_id - this may cause data contamination")
    {:error, :world_id_required}
  end

  def match_best(text, world_id, user_id, cohort_id) do
    # Gather matches from all applicable scopes (most specific to least)
    global_matches = match_scope(:global, nil, text)
    world_matches = match_scope(:world, world_id, text)
    cohort_matches = if cohort_id, do: match_scope(:cohort, cohort_id, text), else: []
    user_matches = if user_id, do: match_scope(:user, user_id, text), else: []

    all_matches =
      (global_matches ++ world_matches ++ cohort_matches ++ user_matches)
      |> Enum.map(&apply_scope_cap/1)
      |> Enum.sort_by(fn {_h, conf} -> -conf end)

    case all_matches do
      [{heuristic, confidence} | _] ->
        # Record usage
        record_usage(heuristic.id)
        {:ok, heuristic, confidence}

      [] ->
        {:error, :no_match}
    end
  end

  @doc """
  Matches input against a specific scope.

  Returns list of {heuristic, confidence} tuples.
  """
  def match_scope(scope, scope_id, text) do
    table = get_table(scope)

    if :ets.whereis(table) != :undefined do
      :ets.tab2list(table)
      |> Enum.filter(fn {_id, h} ->
        not h.deprecated and
          (scope == :global or h.scope_id == scope_id)
      end)
      |> Enum.map(fn {_id, h} ->
        confidence = calculate_match_confidence(h, text)
        {h, confidence}
      end)
      |> Enum.filter(fn {_, conf} -> conf > 0.3 end)
    else
      []
    end
  end

  @doc """
  Adds a new heuristic to the store.

  For learned heuristics (non-global scope), world_id is required.
  Global heuristics are only loaded from seeded data.

  ## Options
  - `:world_id` - Required for learned heuristics (world/cohort/user scope)
  - `:scope` - One of :global, :world, :cohort, :user (default: :world)
  - `:scope_id` - For cohort/user scope, the specific ID
  - `:source` - :seeded or :learned (default: :learned)
  """
  def add_heuristic(pattern, conclusion, opts \\ []) do
    world_id = Keyword.get(opts, :world_id)
    scope = Keyword.get(opts, :scope, :world)

    # Require world_id for non-global scopes
    if scope != :global and is_nil(world_id) do
      Logger.warning("HeuristicStore.add_heuristic called without world_id for scope #{scope}")
      {:error, :world_id_required}
    else
      GenServer.call(__MODULE__, {:add_heuristic, pattern, conclusion, opts}, 5_000)
    end
  end

  @doc """
  Records a success for a heuristic.
  """
  def record_success(heuristic_id) do
    GenServer.cast(__MODULE__, {:record_outcome, heuristic_id, :success})
  end

  @doc """
  Records a failure for a heuristic.
  """
  def record_failure(heuristic_id) do
    GenServer.cast(__MODULE__, {:record_outcome, heuristic_id, :failure})
  end

  @doc """
  Gets a heuristic by ID.
  """
  def get(heuristic_id) do
    # Search all tables
    Enum.find_value([@global_table, @world_table, @cohort_table, @user_table], fn table ->
      if :ets.whereis(table) != :undefined do
        case :ets.lookup(table, heuristic_id) do
          [{_, heuristic}] -> heuristic
          [] -> nil
        end
      else
        nil
      end
    end)
  end

  @doc """
  Lists all heuristics, optionally filtered by scope.
  """
  def list(scope \\ nil) do
    tables =
      case scope do
        :global -> [@global_table]
        :cohort -> [@cohort_table]
        :user -> [@user_table]
        nil -> [@global_table, @cohort_table, @user_table]
      end

    Enum.flat_map(tables, fn table ->
      if :ets.whereis(table) != :undefined do
        :ets.tab2list(table) |> Enum.map(&elem(&1, 1))
      else
        []
      end
    end)
  end

  @doc "Returns true if the HeuristicStore is ready to accept requests."
  def ready?(name \\ __MODULE__) do
    try do
      GenServer.call(name, :ready?, 100)
    catch
      :exit, _ -> false
    end
  end

  @doc """
  Returns statistics about the heuristic store.
  """
  def stats do
    GenServer.call(__MODULE__, :stats, 5_000)
  end

  @doc """
  Checks if a heuristic's success rate is healthy.

  Useful for stability self-reflection (ST5).
  """
  def healthy?(heuristic_id) do
    case get(heuristic_id) do
      nil ->
        false

      h ->
        total = h.success_count + h.failure_count
        total < 5 or h.failure_count / total < @max_failure_rate
    end
  end

  @doc """
  Deprecates a heuristic (marks it as inactive).
  """
  def deprecate(heuristic_id) do
    GenServer.call(__MODULE__, {:deprecate, heuristic_id}, 5_000)
  end

  # Server Callbacks

  @impl true
  def init(opts) do
    # Create ETS tables
    :ets.new(@global_table, [:named_table, :public, :set, read_concurrency: true])
    :ets.new(@world_table, [:named_table, :public, :set, read_concurrency: true])
    :ets.new(@cohort_table, [:named_table, :public, :set, read_concurrency: true])
    :ets.new(@user_table, [:named_table, :public, :set, read_concurrency: true])
    :ets.new(@stats_table, [:named_table, :public, :set, read_concurrency: true])

    # Load seeded heuristics (global scope - apply to all worlds)
    # Default to data/ folder where seeded_heuristics.json is generated by scripts/generate_heuristics.py
    seeded_path = Keyword.get(opts, :seeded_path, "data/heuristics/seeded_heuristics.json")
    load_seeded_heuristics(seeded_path)

    # Load world-specific heuristics from training world folders
    worlds_path = Keyword.get(opts, :worlds_path, "priv/training_worlds")
    load_world_heuristics(worlds_path)

    # Initialize stats
    :ets.insert(@stats_table, {:total_matches, 0})
    :ets.insert(@stats_table, {:fast_path_hits, 0})

    Logger.info("HeuristicStore started", %{
      global_count: :ets.info(@global_table, :size),
      world_count: :ets.info(@world_table, :size),
      cohort_count: :ets.info(@cohort_table, :size),
      user_count: :ets.info(@user_table, :size)
    })

    {:ok, %{seeded_path: seeded_path, worlds_path: worlds_path}}
  end

  @impl true
  def handle_call(:ready?, _from, state) do
    {:reply, true, state}
  end

  @impl true
  def handle_call({:add_heuristic, pattern, conclusion, opts}, _from, state) do
    scope = Keyword.get(opts, :scope, :world)
    scope_id = Keyword.get(opts, :scope_id)
    world_id = Keyword.get(opts, :world_id)
    source = Keyword.get(opts, :source, :learned)

    heuristic = %Heuristic{
      id: generate_id(),
      scope: scope,
      scope_id: scope_id,
      world_id: world_id,
      pattern: pattern,
      conclusion: conclusion,
      source: source,
      max_activation_boost: get_scope_config(scope).max_boost,
      created_at: System.system_time(:millisecond),
      last_updated: System.system_time(:millisecond)
    }

    table = get_table(scope)
    :ets.insert(table, {heuristic.id, heuristic})

    # Persist world heuristics to disk
    if scope == :world and world_id do
      persist_world_heuristics(world_id, state.worlds_path)
    end

    Logger.debug("Added heuristic", %{id: heuristic.id, scope: scope, world_id: world_id, pattern: pattern})

    {:reply, {:ok, heuristic}, state}
  end

  @impl true
  def handle_call({:deprecate, heuristic_id}, _from, state) do
    result =
      Enum.find_value([@global_table, @cohort_table, @user_table], fn table ->
        if :ets.whereis(table) != :undefined do
          case :ets.lookup(table, heuristic_id) do
            [{id, heuristic}] ->
              updated = %{
                heuristic
                | deprecated: true,
                  last_updated: System.system_time(:millisecond)
              }

              :ets.insert(table, {id, updated})
              {:ok, updated}

            [] ->
              nil
          end
        else
          nil
        end
      end)

    {:reply, result || {:error, :not_found}, state}
  end

  @impl true
  def handle_call(:stats, _from, state) do
    stats = %{
      global: %{
        count: :ets.info(@global_table, :size),
        active: count_active(@global_table)
      },
      cohort: %{
        count: :ets.info(@cohort_table, :size),
        active: count_active(@cohort_table)
      },
      user: %{
        count: :ets.info(@user_table, :size),
        active: count_active(@user_table)
      },
      total_matches: get_stat(:total_matches),
      fast_path_hits: get_stat(:fast_path_hits)
    }

    {:reply, stats, state}
  end

  @impl true
  def handle_cast({:record_outcome, heuristic_id, outcome}, state) do
    Enum.find([@global_table, @cohort_table, @user_table], fn table ->
      if :ets.whereis(table) != :undefined do
        case :ets.lookup(table, heuristic_id) do
          [{id, heuristic}] ->
            updated =
              case outcome do
                :success ->
                  %{heuristic | success_count: heuristic.success_count + 1}

                :failure ->
                  %{heuristic | failure_count: heuristic.failure_count + 1}
              end
              |> Map.put(:last_updated, System.system_time(:millisecond))

            # Check if should deprecate
            updated =
              if should_deprecate?(updated) do
                Logger.info("Deprecating heuristic due to high failure rate", %{id: id})
                %{updated | deprecated: true}
              else
                updated
              end

            :ets.insert(table, {id, updated})
            true

          [] ->
            false
        end
      else
        false
      end
    end)

    {:noreply, state}
  end

  # Private functions

  defp get_table(:global), do: @global_table
  defp get_table(:world), do: @world_table
  defp get_table(:cohort), do: @cohort_table
  defp get_table(:user), do: @user_table

  defp get_scope_config(scope), do: Map.get(@scope_config, scope)

  defp apply_scope_cap({heuristic, confidence}) do
    max_boost = get_scope_config(heuristic.scope).max_boost
    capped_confidence = min(confidence, max_boost + 0.5)
    {heuristic, capped_confidence}
  end

  defp calculate_match_confidence(heuristic, text) do
    pattern = heuristic.pattern
    lower_text = String.downcase(text)

    # Check different pattern types
    phrase_match = check_phrase_match(pattern, lower_text)
    first_word_match = check_first_word_match(pattern, lower_text)
    keyword_match = check_keyword_match(pattern, lower_text)
    word_count_match = check_word_count_match(pattern, text)

    # Combine matches
    base_confidence =
      cond do
        phrase_match >= 0.8 -> phrase_match
        first_word_match >= 0.7 and word_count_match -> first_word_match + 0.1
        keyword_match >= 0.5 -> keyword_match
        true -> 0.0
      end

    # Apply success rate bonus
    if base_confidence > 0 and heuristic.success_count > 0 do
      total = heuristic.success_count + heuristic.failure_count
      success_rate = heuristic.success_count / total
      base_confidence * (0.7 + 0.3 * success_rate)
    else
      base_confidence
    end
  end

  defp check_phrase_match(%{phrase: phrase}, text) when is_binary(phrase) do
    phrase_tokens = phrase |> String.downcase() |> Tokenizer.tokenize_normalized(min_length: 1)
    text_tokens = Tokenizer.tokenize_normalized(text, min_length: 1)

    if phrase_tokens != [] and
         Enum.all?(phrase_tokens, fn pt -> Enum.any?(text_tokens, &(&1 == pt)) end) do
      0.9
    else
      0.0
    end
  end

  defp check_phrase_match(_, _), do: 0.0

  defp check_first_word_match(%{first_word: words}, text) when is_list(words) do
    first = text |> Tokenizer.split_words() |> List.first() || ""
    if String.downcase(first) in words, do: 0.8, else: 0.0
  end

  defp check_first_word_match(_, _), do: 0.0

  defp check_keyword_match(%{keywords: keywords}, text) when is_list(keywords) do
    text_words = text |> Tokenizer.tokenize_normalized(min_length: 1) |> MapSet.new()
    matches = Enum.count(keywords, fn kw -> MapSet.member?(text_words, String.downcase(kw)) end)

    cond do
      matches >= 2 -> 0.8
      matches == 1 -> 0.6
      true -> 0.0
    end
  end

  defp check_keyword_match(_, _), do: 0.0

  defp check_word_count_match(%{word_count: range}, text) when is_struct(range, Range) do
    count = text |> Tokenizer.split_words() |> length()
    count in range
  end

  defp check_word_count_match(_, _), do: true

  defp should_deprecate?(heuristic) do
    total = heuristic.success_count + heuristic.failure_count

    cond do
      total < 5 ->
        false

      heuristic.failure_count / total > @max_failure_rate ->
        true

      heuristic.last_used &&
          System.system_time(:millisecond) - heuristic.last_used >
            @deprecation_days * 24 * 60 * 60 * 1000 ->
        true

      true ->
        false
    end
  end

  defp record_usage(heuristic_id) do
    # Update last_used timestamp
    Enum.find([@global_table, @cohort_table, @user_table], fn table ->
      if :ets.whereis(table) != :undefined do
        case :ets.lookup(table, heuristic_id) do
          [{id, heuristic}] ->
            updated = %{heuristic | last_used: System.system_time(:millisecond)}
            :ets.insert(table, {id, updated})
            true

          [] ->
            false
        end
      else
        false
      end
    end)

    # Update stats
    :ets.update_counter(@stats_table, :total_matches, 1, {{:total_matches, 0}})
    :ets.update_counter(@stats_table, :fast_path_hits, 1, {{:fast_path_hits, 0}})
  end

  defp count_active(table) do
    if :ets.whereis(table) != :undefined do
      :ets.tab2list(table)
      |> Enum.count(fn {_, h} -> not h.deprecated end)
    else
      0
    end
  end

  defp get_stat(key) do
    case :ets.lookup(@stats_table, key) do
      [{_, value}] -> value
      [] -> 0
    end
  end

  defp generate_id do
    :crypto.strong_rand_bytes(8) |> Base.encode16(case: :lower)
  end

  defp load_seeded_heuristics(path) do
    case File.read(path) do
      {:ok, content} ->
        case Jason.decode(content) do
          {:ok, heuristics} when is_list(heuristics) ->
            Enum.each(heuristics, fn h ->
              heuristic = %Heuristic{
                id: h["id"] || generate_id(),
                scope: :global,
                scope_id: nil,
                pattern: atomize_keys(h["pattern"] || %{}),
                conclusion: atomize_keys(h["conclusion"] || %{}),
                source: :seeded,
                max_activation_boost: 0.40,
                created_at: System.system_time(:millisecond)
              }

              :ets.insert(@global_table, {heuristic.id, heuristic})
            end)

            Logger.info("Loaded seeded heuristics", %{count: length(heuristics)})

          _ ->
            Logger.warning("Failed to parse seeded heuristics")
        end

      {:error, :enoent} ->
        Logger.debug("No seeded heuristics file found at #{path}")

      {:error, reason} ->
        Logger.warning("Failed to load seeded heuristics: #{inspect(reason)}")
    end
  end

  defp load_world_heuristics(worlds_path) do
    # Load heuristics from each training world folder
    if File.dir?(worlds_path) do
      File.ls!(worlds_path)
      |> Enum.filter(fn dir -> File.dir?(Path.join(worlds_path, dir)) end)
      |> Enum.each(fn world_id ->
        heuristics_file = Path.join([worlds_path, world_id, "heuristics.json"])
        load_world_heuristics_file(heuristics_file, world_id)
      end)
    end
  end

  defp load_world_heuristics_file(path, world_id) do
    case File.read(path) do
      {:ok, content} ->
        case Jason.decode(content) do
          {:ok, heuristics} when is_list(heuristics) ->
            Enum.each(heuristics, fn h ->
              heuristic = %Heuristic{
                id: h["id"] || generate_id(),
                scope: :world,
                scope_id: world_id,
                world_id: world_id,
                pattern: atomize_keys(h["pattern"] || %{}),
                conclusion: atomize_keys(h["conclusion"] || %{}),
                source: :learned,
                max_activation_boost: get_scope_config(:world).max_boost,
                success_count: h["success_count"] || 0,
                failure_count: h["failure_count"] || 0,
                created_at: h["created_at"] || System.system_time(:millisecond),
                last_updated: h["last_updated"]
              }

              :ets.insert(@world_table, {heuristic.id, heuristic})
            end)

            Logger.debug("Loaded world heuristics", %{world_id: world_id, count: length(heuristics)})

          _ ->
            :ok
        end

      {:error, :enoent} ->
        # No heuristics file for this world - that's fine
        :ok

      {:error, reason} ->
        Logger.warning("Failed to load world heuristics for #{world_id}: #{inspect(reason)}")
    end
  end

  defp persist_world_heuristics(world_id, worlds_path) do
    # Get all heuristics for this world
    world_heuristics =
      :ets.tab2list(@world_table)
      |> Enum.filter(fn {_id, h} -> h.world_id == world_id end)
      |> Enum.map(fn {_id, h} ->
        %{
          "id" => h.id,
          "pattern" => stringify_keys(h.pattern),
          "conclusion" => stringify_keys(h.conclusion),
          "success_count" => h.success_count,
          "failure_count" => h.failure_count,
          "created_at" => h.created_at,
          "last_updated" => h.last_updated
        }
      end)

    # Write to world folder
    world_path = Path.join(worlds_path, world_id)
    File.mkdir_p!(world_path)

    heuristics_file = Path.join(world_path, "heuristics.json")
    File.write!(heuristics_file, Jason.encode!(world_heuristics, pretty: true))

    Logger.debug("Persisted world heuristics", %{world_id: world_id, count: length(world_heuristics)})
  rescue
    e ->
      Logger.warning("Failed to persist world heuristics: #{inspect(e)}")
  end

  defp stringify_keys(map) when is_map(map) do
    Map.new(map, fn
      {k, v} when is_atom(k) -> {Atom.to_string(k), stringify_keys(v)}
      {k, v} -> {k, stringify_keys(v)}
    end)
  end

  defp stringify_keys(list) when is_list(list) do
    Enum.map(list, &stringify_keys/1)
  end

  defp stringify_keys(value), do: value

  defp atomize_keys(map) when is_map(map) do
    Map.new(map, fn
      {k, v} when is_binary(k) ->
        {safe_atomize_key(k), atomize_keys(v)}
      {k, v} -> {k, atomize_keys(v)}
    end)
  end

  defp atomize_keys(list) when is_list(list) do
    Enum.map(list, &atomize_keys/1)
  end

  defp atomize_keys(value), do: value

  defp safe_atomize_key(k) when is_binary(k) do
    String.to_existing_atom(k)
  rescue
    ArgumentError -> k
  end
end
