defmodule Brain.ML.KnowledgeGraph.TripleScorer do
  @moduledoc """
  Scores knowledge graph triples (head, relation, tail) for validity using
  a BiLSTM encoder.

  Architecture:
      Input: "[HEAD] entity_name [REL] relation_type [TAIL] entity_name"
        -> Tokenize -> Embedding -> BiLSTM
        -> Masked mean pool -> Dense(128) -> ReLU -> Dropout -> Dense(1) -> Sigmoid
        -> Binary cross-entropy loss

  Trained with negative sampling: positive triples from the knowledge graph,
  negatives generated by corrupting head or tail entities.

  Follows the project's `ready?()` pattern with 100ms timeout.
  """

  use GenServer
  require Logger

  alias Brain.ML.Tokenizer

  @default_embedding_dim 64
  @default_hidden_dim 128
  @default_max_seq_length 32
  @default_epochs 50
  @default_learning_rate 0.001
  @special_tokens ["[HEAD]", "[REL]", "[TAIL]", "[PAD]"]

  defstruct [:model, :params, :vocab, :config, :ready]

  # --- Public API ---

  def start_link(opts \\ []) do
    name = Keyword.get(opts, :name, __MODULE__)
    GenServer.start_link(__MODULE__, opts, name: name)
  end

  def ready?(name \\ __MODULE__) do
    try do
      GenServer.call(name, :ready?, 100)
    catch
      :exit, _ -> false
    end
  end

  @doc """
  Score a triple for validity.

  Returns `{:ok, score}` where score is in (0, 1).
  Higher scores indicate more likely valid triples.
  """
  def score(head, relation, tail, name \\ __MODULE__) do
    try do
      GenServer.call(name, {:score, head, relation, tail}, 5_000)
    catch
      :exit, _ -> {:error, :not_ready}
    end
  end

  @doc """
  Score multiple triples in batch.

  Returns `{:ok, [score]}`.
  """
  def score_batch(triples, name \\ __MODULE__) do
    try do
      GenServer.call(name, {:score_batch, triples}, 10_000)
    catch
      :exit, _ -> {:error, :not_ready}
    end
  end

  def reload(name \\ __MODULE__) do
    GenServer.call(name, :reload, 30_000)
  end

  @doc """
  Build the triple scoring Axon model.

  ## Parameters
    - `vocab_size` - Size of token vocabulary
    - `opts` - Options:
      - `:embedding_dim` - Embedding dimension (default: #{@default_embedding_dim})
      - `:hidden_dim` - LSTM hidden dimension (default: #{@default_hidden_dim})
      - `:max_seq_length` - Maximum sequence length (default: #{@default_max_seq_length})
  """
  def build_model(vocab_size, opts \\ []) do
    embedding_dim = Keyword.get(opts, :embedding_dim, @default_embedding_dim)
    hidden_dim = Keyword.get(opts, :hidden_dim, @default_hidden_dim)
    max_seq_length = Keyword.get(opts, :max_seq_length, @default_max_seq_length)

    input = Axon.input("input", shape: {nil, max_seq_length})
    mask_input = Axon.input("mask", shape: {nil, max_seq_length, 1})

    encoder = input
    |> Axon.embedding(vocab_size, embedding_dim, name: "embedding")
    |> Axon.lstm(hidden_dim, name: "lstm")
    |> then(fn {seq, _state} -> seq end)

    pooled = Axon.layer(
      fn encoder_out, mask, _opts ->
        masked = Nx.multiply(encoder_out, mask)
        sum = Nx.sum(masked, axes: [1])
        count = Nx.sum(mask, axes: [1]) |> Nx.max(1)
        Nx.divide(sum, count)
      end,
      [encoder, mask_input],
      name: "masked_mean_pool"
    )

    pooled
    |> Axon.dense(128, activation: :relu, name: "dense1")
    |> Axon.dropout(rate: 0.3, name: "dropout")
    |> Axon.dense(1, name: "output")
    |> Axon.sigmoid(name: "score")
  end

  @doc """
  Train the triple scorer on positive and negative triples.

  ## Parameters
    - `positive_triples` - List of `{head, relation, tail}` string tuples
    - `opts` - Training options:
      - `:epochs` - Number of training epochs (default: #{@default_epochs})
      - `:learning_rate` - Learning rate (default: #{@default_learning_rate})
      - `:neg_ratio` - Negative-to-positive ratio (default: 5)
      - `:verbose` - Print per-epoch loss (default: false)
  """
  def train(positive_triples, opts \\ []) do
    epochs = Keyword.get(opts, :epochs, @default_epochs)
    lr = Keyword.get(opts, :learning_rate, @default_learning_rate)
    neg_ratio = Keyword.get(opts, :neg_ratio, 5)

    entities = positive_triples
    |> Enum.flat_map(fn {h, _r, t} -> [h, t] end)
    |> Enum.uniq()

    vocab = build_vocab(positive_triples)
    vocab_size = map_size(vocab)

    model = build_model(vocab_size,
      embedding_dim: Keyword.get(opts, :embedding_dim, @default_embedding_dim),
      hidden_dim: Keyword.get(opts, :hidden_dim, @default_hidden_dim)
    )

    positive_set = MapSet.new(positive_triples)
    negatives = generate_negatives(positive_triples, entities, positive_set, neg_ratio)

    all_examples = Enum.map(positive_triples, &{&1, 1.0}) ++
                   Enum.map(negatives, &{&1, 0.0})

    shuffled = Enum.shuffle(all_examples)
    {inputs, labels} = encode_examples(shuffled, vocab)

    train_data = Stream.repeatedly(fn ->
      {inputs, labels}
    end)

    optimizer = Polaris.Optimizers.adam(learning_rate: lr)
    log_interval = if Keyword.get(opts, :verbose, false), do: 1, else: 0

    params = model
    |> Axon.Loop.trainer(:binary_cross_entropy, optimizer, log: log_interval)
    |> Axon.Loop.run(train_data, Axon.ModelState.empty(), epochs: epochs, iterations: 1, compiler: EXLA)

    params = transfer_to_binary_backend(params)

    config = %{
      vocab_size: vocab_size,
      embedding_dim: Keyword.get(opts, :embedding_dim, @default_embedding_dim),
      hidden_dim: Keyword.get(opts, :hidden_dim, @default_hidden_dim),
      max_seq_length: @default_max_seq_length
    }

    {:ok, model, params, vocab, config}
  end

  @doc """
  Save a trained model to disk.
  """
  def save_model(params, vocab, config, path) do
    File.mkdir_p!(Path.dirname(path))
    data = %{params: params, vocab: vocab, config: config}
    File.write!(path, :erlang.term_to_binary(data))
    :ok
  end

  @doc """
  Load a trained model from disk.
  """
  def load_model(path) do
    case File.read(path) do
      {:ok, binary} ->
        data = :erlang.binary_to_term(binary)
        {:ok, %{data | params: ensure_model_state(data.params)}}

      {:error, reason} ->
        {:error, reason}
    end
  end

  # --- GenServer Callbacks ---

  @impl true
  def init(opts) do
    world_id = Keyword.get(opts, :world_id, "default")
    state = %__MODULE__{ready: false}

    case try_load(world_id) do
      {:ok, loaded_state} -> {:ok, loaded_state}
      {:error, _} -> {:ok, state}
    end
  end

  @impl true
  def handle_call(:ready?, _from, state) do
    {:reply, state.ready, state}
  end

  def handle_call({:score, _head, _relation, _tail}, _from, %{ready: false} = state) do
    {:reply, {:error, :not_ready}, state}
  end

  def handle_call({:score, head, relation, tail}, _from, state) do
    result = do_score(head, relation, tail, state)
    {:reply, result, state}
  end

  def handle_call({:score_batch, _triples}, _from, %{ready: false} = state) do
    {:reply, {:error, :not_ready}, state}
  end

  def handle_call({:score_batch, triples}, _from, state) do
    scores = Enum.map(triples, fn {h, r, t} ->
      case do_score(h, r, t, state) do
        {:ok, s} -> s
        _ -> 0.5
      end
    end)
    {:reply, {:ok, scores}, state}
  end

  def handle_call(:reload, _from, state) do
    case try_load("default") do
      {:ok, loaded} -> {:reply, :ok, loaded}
      {:error, reason} -> {:reply, {:error, reason}, state}
    end
  end

  # --- Private ---

  defp try_load(world_id) do
    path = model_path(world_id)
    Brain.ML.ModelStore.ensure_local("#{world_id}/kg_lstm/triple_scorer.term", path)

    case load_model(path) do
      {:ok, data} ->
        model = build_model(data.config.vocab_size,
          embedding_dim: data.config.embedding_dim,
          hidden_dim: data.config.hidden_dim
        )

        state = %__MODULE__{
          model: model,
          params: ensure_model_state(data.params),
          vocab: data.vocab,
          config: data.config,
          ready: true
        }
        {:ok, state}

      {:error, reason} ->
        {:error, reason}
    end
  end

  defp do_score(head, relation, tail, state) do
    text = "[HEAD] #{head} [REL] #{relation} [TAIL] #{tail}"
    {input, mask} = encode_single(text, state.vocab, @default_max_seq_length)

    output = Axon.predict(state.model, state.params, %{
      "input" => input,
      "mask" => mask
    }, compiler: EXLA)

    score = output |> Nx.squeeze() |> Nx.to_number()
    {:ok, score}
  end

  defp build_vocab(triples) do
    all_tokens = triples
    |> Enum.flat_map(fn {h, r, t} ->
      tokenize_triple("[HEAD] #{h} [REL] #{r} [TAIL] #{t}")
    end)
    |> Enum.uniq()

    (@special_tokens ++ all_tokens)
    |> Enum.uniq()
    |> Enum.with_index()
    |> Map.new()
  end

  defp encode_examples(examples, vocab) do
    max_len = @default_max_seq_length

    {input_list, label_list} = Enum.unzip(
      Enum.map(examples, fn {{h, r, t}, label} ->
        text = "[HEAD] #{h} [REL] #{r} [TAIL] #{t}"
        tokens = tokenize_triple(text)

        indices = tokens
        |> Enum.take(max_len)
        |> Enum.map(&Map.get(vocab, &1, 0))

        padded = indices ++ List.duplicate(Map.get(vocab, "[PAD]", 0), max_len - length(indices))
        mask = List.duplicate(1.0, min(length(indices), max_len)) ++
               List.duplicate(0.0, max_len - min(length(indices), max_len))

        {%{input: padded, mask: Enum.map(mask, &[&1])}, label}
      end)
    )

    inputs = %{
      "input" => Nx.tensor(Enum.map(input_list, & &1.input), type: :s32),
      "mask" => Nx.tensor(Enum.map(input_list, & &1.mask))
    }

    labels = Nx.tensor(Enum.map(label_list, &[&1]))

    {inputs, labels}
  end

  @doc false
  def encode_single_public(text, vocab) do
    encode_single(text, vocab, @default_max_seq_length)
  end

  defp encode_single(text, vocab, max_len) do
    tokens = tokenize_triple(text)

    indices = tokens
    |> Enum.take(max_len)
    |> Enum.map(&Map.get(vocab, &1, 0))

    padded = indices ++ List.duplicate(Map.get(vocab, "[PAD]", 0), max_len - length(indices))
    mask = List.duplicate(1.0, min(length(indices), max_len)) ++
           List.duplicate(0.0, max_len - min(length(indices), max_len))

    input = Nx.tensor([padded], type: :s32)
    mask_tensor = Nx.tensor([Enum.map(mask, &[&1])])

    {input, mask_tensor}
  end

  defp tokenize_triple(text) do
    split_pattern = @special_tokens
    |> Enum.reject(&(&1 == "[PAD]"))
    |> Enum.map(&Regex.escape/1)
    |> Enum.join("|")

    text
    |> String.split(Regex.compile!("(#{split_pattern})"), include_captures: true, trim: true)
    |> Enum.flat_map(fn segment ->
      if segment in @special_tokens do
        [segment]
      else
        Tokenizer.tokenize_normalized(String.trim(segment))
      end
    end)
  end

  defp generate_negatives(positives, entities, positive_set, ratio) do
    Enum.flat_map(positives, fn {h, r, t} ->
      Stream.repeatedly(fn ->
        if :rand.uniform() > 0.5 do
          corrupt_h = Enum.random(entities)
          {corrupt_h, r, t}
        else
          corrupt_t = Enum.random(entities)
          {h, r, corrupt_t}
        end
      end)
      |> Stream.reject(&MapSet.member?(positive_set, &1))
      |> Enum.take(ratio)
    end)
  end

  defp ensure_model_state(%Axon.ModelState{} = state), do: state
  defp ensure_model_state(params) when is_map(params), do: Axon.ModelState.new(params)

  defp transfer_to_binary_backend(%Axon.ModelState{} = model_state) do
    data = model_state.data
    |> Map.new(fn {key, value} -> {key, transfer_value(value)} end)
    %{model_state | data: data}
  end

  defp transfer_to_binary_backend(params) when is_map(params) do
    Map.new(params, fn {key, value} -> {key, transfer_value(value)} end)
  end

  defp transfer_value(%Nx.Tensor{} = tensor) do
    Nx.backend_transfer(tensor, Nx.BinaryBackend)
  end

  defp transfer_value(map) when is_map(map) do
    Map.new(map, fn {k, v} -> {k, transfer_value(v)} end)
  end

  defp transfer_value(other), do: other

  defp model_path(world_id) do
    priv = :code.priv_dir(:brain) |> to_string()
    Path.join([priv, "ml_models", world_id, "kg_lstm", "triple_scorer.term"])
  end
end
