defmodule Brain.Lexicon.ConceptNet do
  @moduledoc """
  Query API for ConceptNet relations stored in ETS.

  The `:lexicon_conceptnet` table is populated by `Brain.Lexicon.Loader`
  from a pre-built `.term` file generated by `mix ingest_lexicon`.

  ConceptNet relations include: IsA, PartOf, HasA, UsedFor, CapableOf,
  AtLocation, Causes, HasProperty, MotivatedByGoal, CreatedBy,
  DefinedAs, SymbolOf, MadeOf, ReceivesAction, etc.
  """

  @conceptnet_table :lexicon_conceptnet

  @doc """
  Returns all ConceptNet relations for a concept.

  Returns `%{relation_type => [related_concepts]}` or empty map.
  """
  def relations(concept) when is_binary(concept) do
    normalized = String.downcase(concept)

    case safe_lookup(normalized) do
      nil -> %{}
      rels -> rels
    end
  end

  @doc """
  Returns related concepts for a specific relation type.

  Example: `related("dog", "IsA")` might return `["animal", "pet", "canine"]`.
  """
  def related(concept, relation_type) when is_binary(concept) and is_binary(relation_type) do
    case relations(concept) do
      %{} = rels -> Map.get(rels, relation_type, [])
    end
  end

  @doc """
  Returns the count of relations by type for a concept.
  """
  def relation_counts(concept) when is_binary(concept) do
    concept
    |> relations()
    |> Enum.map(fn {rel_type, concepts} -> {rel_type, length(concepts)} end)
    |> Map.new()
  end

  @doc """
  Returns true if the concept has any ConceptNet data.
  """
  def has_data?(concept) when is_binary(concept) do
    relations(concept) != %{}
  end

  @doc """
  Returns all relation types present for a concept.
  """
  def relation_types(concept) when is_binary(concept) do
    concept |> relations() |> Map.keys()
  end

  defp safe_lookup(key) do
    try do
      case :ets.lookup(@conceptnet_table, key) do
        [{^key, relations}] -> relations
        _ -> nil
      end
    catch
      :error, :badarg -> nil
    end
  end
end
